"""added natinality column

Revision ID: 4337f4ec45e7
Revises: 
Create Date: 2021-04-29 15:55:49.234447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4337f4ec45e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_details', sa.Column('nationality', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_details', 'nationality')
    # ### end Alembic commands ###
